-- MySQL Script generated by MySQL Workbench
-- Sat Aug  9 14:15:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema agropatriaapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agropatriaapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agropatriaapp` DEFAULT CHARACTER SET utf8mb3 ;
USE `agropatriaapp` ;

-- -----------------------------------------------------
-- Table `agropatriaapp`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `url` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_bin;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`cuentas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_bin;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `imagen` TEXT NULL DEFAULT NULL,
  `precio` INT NULL DEFAULT NULL,
  `condicion` INT NULL DEFAULT NULL,
  `clasificacion` TEXT NULL DEFAULT NULL,
  `region` TEXT NULL DEFAULT NULL,
  `categoria` INT NULL DEFAULT NULL,
  `moneda` VARCHAR(50) NOT NULL DEFAULT '$',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 300
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_bin;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`sessions` (
  `session_id` VARCHAR(128) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NOT NULL,
  `expires` INT UNSIGNED NOT NULL,
  `data` MEDIUMTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_bin' NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_bin;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`sliders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`sliders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` TEXT NULL DEFAULT NULL,
  `botonText` TEXT NULL DEFAULT NULL,
  `botonUrl` TEXT NULL DEFAULT NULL,
  `Slogan` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_bin;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`textos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`textos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf16
COLLATE = utf16_bin;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`planes` (
  `id_plan` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  `precio` INT(11) NULL,
  `duracion_dias` INT(11) NULL,
  `cantidad_public` INT(11) NULL,
  PRIMARY KEY (`id_plan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`vendedor` (
  `cuentas_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `razon` VARCHAR(45) NULL,
  `cuit_vendedor` INT(11) NULL,
  `localidad_vendedor` VARCHAR(45) NULL,
  `provincia_vendedor` VARCHAR(45) NULL,
  `logo_vendedor` VARCHAR(45) NULL,
  `planes_id_plan` INT NOT NULL,
  PRIMARY KEY (`cuentas_id`, `planes_id_plan`),
  INDEX `fk_vendedor_planes1_idx` (`planes_id_plan` ASC) VISIBLE,
  CONSTRAINT `fk_vendedor_cuentas`
    FOREIGN KEY (`cuentas_id`)
    REFERENCES `agropatriaapp`.`cuentas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_planes1`
    FOREIGN KEY (`planes_id_plan`)
    REFERENCES `agropatriaapp`.`planes` (`id_plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`coberturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`coberturas` (
  `id_cobertura` INT NOT NULL,
  `nombre_cobertura` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cobertura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`seguros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`seguros` (
  `id_seguros` INT NOT NULL,
  `nombre_seguro` VARCHAR(45) NULL,
  `id_cobertura` INT NOT NULL,
  PRIMARY KEY (`id_seguros`, `id_cobertura`),
  INDEX `fk_seguros_coberturas1_idx` (`id_cobertura` ASC) VISIBLE,
  CONSTRAINT `fk_seguros_coberturas1`
    FOREIGN KEY (`id_cobertura`)
    REFERENCES `agropatriaapp`.`coberturas` (`id_cobertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`Publicacion` (
  `idPublicacion` INT NOT NULL,
  `nombrePublicacion` VARCHAR(45) NULL,
  `descripcionPublic` VARCHAR(45) NULL,
  `modeloPublicacion` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`idPublicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`publicacion` (
  `publicacion_id` INT NOT NULL AUTO_INCREMENT,
  `productos_id` INT NOT NULL,
  `vendedor_cuentas_id` INT NOT NULL,
  `vendido` TINYINT NOT NULL,
  PRIMARY KEY (`publicacion_id`, `productos_id`, `vendedor_cuentas_id`),
  INDEX `fk_publicacion_has_productos_productos1_idx` (`productos_id` ASC) VISIBLE,
  INDEX `fk_publicacion_vendedor1_idx` (`vendedor_cuentas_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicacion_has_productos_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `agropatriaapp`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publicacion_vendedor1`
    FOREIGN KEY (`vendedor_cuentas_id`)
    REFERENCES `agropatriaapp`.`vendedor` (`cuentas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`PlanesCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`PlanesCategoria` (
  `planes_id_plan` INT NOT NULL,
  `categorias_id` INT NOT NULL,
  PRIMARY KEY (`planes_id_plan`, `categorias_id`),
  INDEX `fk_PlanesCategoria_planes1_idx` (`planes_id_plan` ASC) VISIBLE,
  INDEX `fk_PlanesCategoria_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  CONSTRAINT `fk_PlanesCategoria_planes1`
    FOREIGN KEY (`planes_id_plan`)
    REFERENCES `agropatriaapp`.`planes` (`id_plan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PlanesCategoria_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `agropatriaapp`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agropatriaapp`.`busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agropatriaapp`.`busqueda` (
  `id_busqueda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`id_busqueda`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
