name: Build and Push Docker Image to Custom Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login a tu registry custom
      - name: Log in to Custom Registry
        uses: docker/login-action@v2
        with:
          registry: registry.qrgross.com

      # 3. Build de la imagen
      - name: Build Docker image
        run: |
          docker build -t registry.qrgross.com/agropatria-api:latest ./agropatriaapi

      # 4. Push al registry
      - name: Push Docker image
        run: |
          docker push registry.qrgross.com/agropatria-api:latest
